region: "eu-central-1"
vpc_cidr: "10.0.0.0/16"
eks_cluster_name: "test-cluster"
eks_ec2_volume_size: "100G"
eks_keypair_name: "eu-central-1-alex-key"
eks_max_capacity: 1
eks_min_capacity: 1
eks_node_ami: "ami-0e70dc9d2c457f1c8"
eks_node_type: "t3.medium"